network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.0.250/24]
      gateway4: 192.168.0.254
      nameservers:
        addresses: [192.168.0.254,4.2.2.2]

